DojoSecrets/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^secrets/', include('apps.secret.urls', namespace='secret')),
    url(r'^', include('apps.log.urls', namespace='log')),
]

apps/log/urls.py
from django.conf.urls import url
from . import views

app_name = "log"
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^reg$', views.reg, name='reg'),
    url(r'^login$', views.login, name='login'),
    url(r'^user_info/(?P<id>\d+)$', views.user_info, name='user_info'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^delete_user$', views.delete_user, name='delete_user'),
    url(r'^update_user$', views.update_user, name='update_user'),
    url(r'^start_reg$', views.start_reg, name='start_reg'),
    url(r'^start_log$', views.start_log, name='start_log'),

]

apps/secret/urls.py
from django.conf.urls import url
from . import views

app_name = 'secret'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^post$', views.post, name='post'),
    url(r'^like/(?P<sec_id>\d+)$', views.like, name='like'),
    url(r'^delete/(?P<mess_id>\d+)$', views.delete, name='delete'),
    url(r'^popular$', views.popular, name='popular'),

]

apps/secret/models.py
from __future__ import unicode_literals

from django.db import models
from ..log.models import User


# Create your models here.
class SecretManager(models.Manager):
    def post(self, postData, id):
            errors = []
            if len(postData['message']) < 1:
                errors.append('Message cannot be empty')

            if errors:
                return (False, errors)

            else:
                print postData['message']
                user = User.objects.get(id=id)
                newobj = Secret.objects.create(
                  message=postData['message'],
                  user_message=user,

                )
                return (True, newobj)
    def like(self, request, id):
            errors = []
            try:
                curr_user = User.objects.get(id=request.session['id'])
                like = Secret.objects.get(id=id)
                like.liked_by.add(curr_user)
                like.save()
                print "liked"
                return (True, newobj)
            except:
                if errors:
                    return (False, errors)

    def delete(self, request, id):
        errors = []
        try:
            message = Secret.objects.get(id=id)
            print message
            message.delete()
            return True
        except:

            return False

class Secret(models.Model):
    message = models.TextField(max_length=1000)
    user_message = models.ForeignKey(User, on_delete=models.CASCADE, related_name="secrets")
    liked_by = models.ManyToManyField(User, related_name="liked")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = SecretManager()

apps/secret/views.py
from django.shortcuts import render, redirect, reverse
from django.db.models import F, Count, Value

from .models import Secret, User
# Create your views here.
def index(request):
    context = {
    'secrets': Secret.objects.all().order_by('-created_at')[:10],
    'user': User.objects.get(id=request.session['id']),
    'status': 'main'
    }
    return render(request, 'secret/index.html', context)


def post(request):
    if request.method == 'POST':
        valid, data = Secret.objects.post(request.POST, request.session['id'])
        if valid:
            return redirect(reverse('secret:index'))
        else:
            for err in data:
                messages.error(request, err)
            return redirect(reverse('secret:index'))

def like(request, sec_id):
    liked = Secret.objects.like(request, sec_id)
    return redirect('secret:index')

def popular(request):
    context = {
    'secrets': Secret.objects.annotate(num_all_likes=Count('liked_by')).order_by('-num_all_likes'),
    'user': User.objects.get(id=request.session['id']),
    'status': 'popular'
    }
    return render(request, 'secret/index.html', context)

def delete(request, mess_id):
    print "wtf"
    delete = Secret.objects.delete(request, mess_id)
    return redirect('secret:index')

apps/secret/templates/secret/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Secrets</title>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'secret/css/secret.css' %}"media="screen" title="no title"  charset="utf-8">
        <style media="screen" type="text/css">
            #sec {
                border: 1px solid black;
                height: 150px;
                width: 500px;
            }
        </style>
    </head>
    <body>
        {% if status == 'main' %}
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
              {% endif %}
            <div id="wrapper">
            <h1>Hellow {{user.first_name}}!</h1>
            <form class="" action="{% url 'secret:post' %}" method="post">
                {% csrf_token %}
                <textarea name="message" rows="8" cols="80">Your secret here...</textarea><br>
                <button type="submit" name="button">Post</button>
            </form>
            <a href="{% url 'secret:popular' %}">Most popular secrets</a>
            <a href="{% url 'log:logout' %}">Logout</a>
            <h3>Recent Secrets: </h3>
              {% for secret in secrets %}
                 <div id="sec">
                    <p>{{ secret.message }} Posted at {{ secret.created_at }} {{secret.liked_by.all.count}} likes.</p>
                    {% if user in secret.liked_by.all %}
                      <p>You liked this</p>
                    {% endif %}
                    {% if secret.user_message == user %}
                    <p> You posted this <a href="{% url 'secret:delete' secret.id %}">Delete</a></p>
                    {% else %}
                      {% if user not in secret.liked_by.all %}
                        <a href="{% url 'secret:like' secret.id %}">Like</a>
                      {% endif %}
                    {% endif %}
                </div>
              {% endfor %}
            </div>
        {% endif %}
        {% if status == 'popular' %}
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
           {% endif %}
           <div id="popular">
               <h3>Most popular secrets</h3>
               <a href="{% url 'secret:index' %}">Back</a>
               {% for secret in secrets %}
                  <div id="sec">
                     <p>{{ secret.message }} Posted at {{ secret.created_at }} {{secret.liked_by.all.count}} likes.</p>
                     {% if user in secret.liked_by.all %}
                       <p>You liked this</p>
                     {% endif %}
                     {% if secret.user_message == user %}
                     <p> You posted this <a href="{% url 'secret:delete' secret.id %}">Delete</a></p>
                     {% else %}
                       {% if user not in secret.liked_by.all %}
                         <a href="{% url 'secret:like' secret.id %}">Like</a>
                       {% endif %}
                     {% endif %}
                 </div>
               {% endfor %}
             </div>
           </div>
        {% endif %}
    </body>
</html>