DojoSecrets/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^secrets/', include('apps.secret.urls', namespace='secret')),
    url(r'^', include('apps.log.urls', namespace='log')),
]

apps/log/urls.py
from django.conf.urls import url
from . import views

app_name = "log"
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^reg$', views.reg, name='reg'),
    url(r'^login$', views.login, name='login'),
    url(r'^user_info/(?P<id>\d+)$', views.user_info, name='user_info'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^delete_user$', views.delete_user, name='delete_user'),
    url(r'^update_user$', views.update_user, name='update_user'),
    url(r'^start_reg$', views.start_reg, name='start_reg'),
    url(r'^start_log$', views.start_log, name='start_log'),

]

apps/log/models.py
from __future__ import unicode_literals

from django.db import models
import bcrypt
import re
EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9\.\+_-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]*$')

# Create your models here.
class UserManager(models.Manager):
      def register(self, postData):
          errors = []
          exists = User.objects.filter(email=postData['email'])
          if exists:
              errors.append('Email already in database')
              print "in database"
              return (False, errors)
          else:

              if len(postData['first_name']) < 1:
                  errors.append('First name cannot be empty')

              if len(postData['last_name']) < 1:
                 errors.append('Last name cannot be empty')

              if not postData['first_name'].isalpha():
                  errors.append('First Name must only contain letters')

              if not postData['last_name'].isalpha():
                  errors.append('Last Name must only contain letters')

              if not EMAIL_REGEX.match(postData['email']):
                 errors.append('Email must be a valid email')

              if len(postData['password']) < 1:
                  errors.append('Password must not be empty')

              if len(postData['password']) < 8:
                  errors.append('Password to short')

              if len(postData['confirm_password']) < 1:
                  errors.append('Confirm password must not be empty')

              if postData['password'] != postData['confirm_password']:
                  errors.append('Password and Confirm password must match')
              if errors:
                  return (False, errors)
              else:
                  pw = postData['password']
                  hashed_pw = bcrypt.hashpw(pw.encode(), bcrypt.gensalt())
                  newobj = User.objects.create(
                    first_name=postData['first_name'],
                    last_name=postData['last_name'],
                    email=postData['email'],
                    password=hashed_pw,
                  )
                  return (True, newobj)



      def login(self, postData):
        errors = []
        exists = User.objects.filter(email=postData['email'])
        if not exists:
            errors.append('Must be a valid user')
            print "not in database"

        if errors:
                return (False, errors)
        else:
            try:
                if exists:
                    user = User.objects.get(email=postData['email'])
                    password = postData['password']
                if bcrypt.hashpw(password.encode(), user.password.encode()) == user.password.encode():
                    print "success"
                    return (True, user)

            except:
                    print 'something failed', user

        errors.append('incorrect password')
        return (False, errors)

      def delete_user(self, postData):
          user = User.objects.get(id=postData)
          user.delete()
          return True
      def update_user(self, ids, postData):
          errors = []
          exists = User.objects.filter(email=postData['email'])
          if exists:
              errors.append('Email already in database')
              print "in database"
              return (False, errors)
          else:
              user = User.objects.get(id=ids)
              user.first_name = postData['first_name']
              user.last_name = postData['last_name']
              user.email = postData['email']
              user.save()
              return (True, user)
class User(models.Model):
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    email = models.CharField(max_length=45)
    password = models.CharField(max_length=45)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    objects = UserManager()

apps/log/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from .models import User
# Create your views here.
def index(request):
    context = {
        'log': 'log'
    }
    return render(request, 'log/index.html', context)

def start_log(request):
    return redirect(reverse('log:index'))

def start_reg(request):
    context = {
        'log': 'reg'
    }
    return render(request, 'log/index.html', context)
def reg(request):
    if request.method == 'POST':
        valid, data = User.objects.register(request.POST)
        if valid:
            context = {
            'status': "registered"
            }
            request.session['name'] = request.POST['first_name']
            return render(request, 'log/success.html', context)
        else:
            for err in data:
                messages.error(request, err)
            return redirect(reverse('log:start_reg'))

def login(request):
    if request.method == 'POST':
        valid, data = User.objects.login(request.POST)
        if valid:

            user_info = User.objects.login(request.POST)
            context = {
            'first_name': user_info[1].first_name,
            'last_name': user_info[1].last_name,
            'email': user_info[1].email,
            'status': "logged in",
            'id': user_info[1].id
            }
            request.session['id'] = user_info[1].id
            request.session['name'] = user_info[1].first_name
            return render(request, 'log/success.html', context)
        else:
            for err in data:
                messages.error(request, err)
            return redirect(reverse('log:index'))

def user_info(request, id):
    if 'id' in request.session:

        user_info = User.objects.get(id=request.session['id'])
        id = request.session['id']
        context = {
        'first_name': user_info.first_name,
        'last_name': user_info.last_name,
        'email': user_info.email,
        'status': "logged in",
        'id': user_info.id
        }
        return render(request, 'log/user_info.html', context)
    else:
        return redirect(reverse('log:index'))

def delete_user(request):
    if request.method == 'POST':
        id = request.session['id']
        data = User.objects.delete_user(id)
        if data:
            print "deleted user"
            return redirect(reverse('log:index'))
        else:
            print "didnt work!"
            return redirect(reverse('log:index'))

def update_user(request):
    if request.method == 'POST':
        ids = request.session['id']
        valid, data = User.objects.update_user(ids, request.POST)
        if valid:
            messages.success(request, 'Profile details updated. Please log in again')
            return redirect(reverse('log:index'))
        else:

            for err in data:
                messages.error(request, err)

            user = User.objects.get(id=ids)
            context = {
            'first_name': user.first_name,
            'last_name': user.last_name,
            'email': user.email,
            'status': "logged in",
            }
            print "didnt work!"
            return render(request, 'log/success.html', context)
def logout(request):
    request.session.clear()
    return redirect(reverse('log:index'))

apps/log/templates/log/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'log/css/style.css' %}"media="screen" title="no title"  charset="utf-8">
    </head>
    <body>
        <div id="wrapper">
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            {% if log == 'reg' %}
                <h1>Registration</h1>
                <form class="" action="{% url 'log:reg' %}" method="post">
                    {% csrf_token %}
                    <label for="">First Name</label>
                    <input type="text" name="first_name" value=""><br>
                    <label for="">Last Name</label>
                    <input type="text" name="last_name" value=""><br>
                    <label for="">Email</label>
                    <input type="text" name="email" value=""><br>
                    <label for="">Password</label>
                    <input type="text" name="password" value=""><br>
                    <label for="">Confirm Password</label>
                    <input type="text" name="confirm_password" value=""><br>
                    <button type="submit" name="button">Register</button>
                </form>
                <a href="/start_log">Login Here</a>
            {% endif %}
            {% if log == 'log' %}
                <h1>Login</h1>
                <form class="" action="{% url 'log:login' %}" method="post">
                    {% csrf_token %}
                    <label for="">Email</label>
                    <input type="text" name="email" value=""><br>
                    <label for="">Password</label>
                    <input type="text" name="password" value=""><br>
                    <button type="submit" name="button">Login</button>
                </form>

                <a href="{% url 'log:start_reg' %}">Register Here!</a>
            {% endif %}
        </div>
    </body>
</html>

apps/log/templates/log/success.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'log/css/success_style.css' %}"media="screen" title="no title"  charset="utf-8">
    </head>
    </head>
    <body>
        <div id="wrapper">
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            <h1>Welcome, {{request.session.name}}</h1>
            <p>Successfully {{status}}</p>
            {% if status == 'logged in' %}
            <h3>Update your acount info:</h3>
            <a href="{% url 'log:user_info' id=request.session.id %}">Update</a>

            <a href="{% url 'log:logout' %}" id="logout">Log Out</a>
            <h3>Click here to go to secrets!</h3>
            <a href="{% url 'secret:index' %}" id="secret">Secrets!</a>
            {% endif %}
            {% if status == 'registered' %}
                <p>Please log in to see your info.</p>
                <a href="{% url 'log:index' %}">Log in</a>
            {% endif %}
        </div>
    </body>
</html>

apps/log/templates/log/user_info.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'log/css/success_style.css' %}"media="screen" title="no title"  charset="utf-8">
    </head>
    </head>
    <body>
        <div id="wrapper">
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            <h1>Welcome, {{request.session.name}}</h1>
            <h3>User info:</h3>
            <p>First Name: {{first_name}} </p>
            <p>Last Name: {{last_name}}</p>
            <p>Email: {{email}}</p>
            <h3>Update your user info:</h3>
            <form class="" action="{% url 'log:update_user' %}" method="post">
                {% csrf_token %}
                <label for="">First Name:</label>
                <input type="text" name="first_name" value=""><br>
                <label for="">Last Name:</label>
                <input type="text" name="last_name" value=""><br>
                <label for="">Email:</label>
                <input type="text" name="email" value=""><br>
                <button type="submit" name="button">Update User</button>
            </form>
            <h3>Delete your Profile:</h3>
            <form class="" action="{% url 'log:delete_user' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="email" value="{{email}}">
                <button type="submit" name="button">Delete User</button>
            </form>
            <a href="{% url 'log:logout' %}" id="logout">Log Out</a>

        </div>
    </body>
</html>